site_name: Grupo WFG Alterna Academy
theme:
  name: material
  font:
    text: Merriwaether Sans
    code: Red Hat Mono
  palette:
  #darkmode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple
    
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

  features:
    - header.autohide
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path

